# Generated by Django 5.2.5 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
