# Generated by Django 5.2.5 on 2025-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='album_art',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='label',
            field=models.CharField(default='Unsigned', max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='sales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
